### ISSUE TITLE
License / Readme

### ISSUE THREAD

**Issue by ccmsi** [jcmb/RTCM3#1]
Greetings.
I would like to use your RTCM decoder.
What license would you apply to your code and do you have any notes for it ?
Thanks.

**Comment by jcmb** [comment]
It is GPL V3, I do need to add that to the files.

There are a bunch of messages that I need to add support for still, which I hope to get to any day now...

**Comment by ccmsi** [comment]
I have a couple simple fixes. How would you prefer me to provide them in case you are interested ?
Easiest for me for sure is to just commit, if preferred on a branch.

**Comment by jcmb** [comment]
Just commit if that is easier for you

**Comment by ccmsi** [comment]
In this case then, i would need permissions set to push the changes.

**Comment by ccmsi** [comment]
Just to state, i dont have such permission on your repo at this time.
